DATE_FIELD = "date"
WEEK_FIELD = "Weekly"
MONTH_FIELD = "Monthly"
YEAR_FIELD = "Yearly"
DAY_OF_WEEK = "DayOfWeek"

NO_WEEKEND = "NoWeekend"
AVG_LINE = "AvgLine"
ROLLING_AVERAGE = "RollingAverage"
Y_MAX = "YMax"
Y_MIN = "YMin"
BAR_OPTION = "Bar"
BOX_PLOT = "BoxPlot"
MULTI_PLOT = "MultiPlot"
FIRST_DATE = "FirstDate"
LAST_DATE = "LastDate"
GRAPH_TYPES = [BAR_OPTION, BOX_PLOT]

VISUALIZATION_OLD_INPUT_FILENAME = "output.csv"
VISUALIZATION_NEW_INPUT_FILENAME = "newOutput.csv"

NULL_MEANS_MISSING = "NotNull"
NULL_IS_ZERO = "NullIsZero"
SHIFT = "Shift"
NORMALIZE = "Normalize"

PARSER_NULL_VALUE = "null"
PARSER_OUTPUT_FILENAME = "output.csv"
NEW_PARSER_OUTPUT_FILENAME = "newOutput.csv"
PARSER_INPUT_FILENAME = "daily.nnex"
NEW_PARSER_INPUT_FILENAME = "../../dailyDataDec2022.txt"